# Generated by Django 3.1.4 on 2020-12-11 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unica_app', '0003_emailhistorico_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailhistorico',
            old_name='request_information',
            new_name='result',
        ),
        migrations.AddField(
            model_name='emailhistorico',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
