# Generated by Django 3.1.4 on 2020-12-12 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unica_app', '0004_auto_20201211_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailhistorico',
            old_name='emails',
            new_name='text',
        ),
    ]
