# Generated by Django 3.1.4 on 2020-12-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unica_app', '0005_auto_20201212_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='quota',
            new_name='disponibles',
        ),
        migrations.AddField(
            model_name='quota',
            name='procesados',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
