# Generated by Django 3.1.4 on 2020-12-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unica_app', '0006_auto_20201218_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quota',
            old_name='disponibles',
            new_name='disponible',
        ),
    ]
